# Generated by Django 6.0 on 2026-02-16 09:03

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppUserRole',
            fields=[
                ('pk', models.CompositePrimaryKey('user_key', 'role_key', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('asset_category_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('depreciation_method', models.TextField()),
                ('useful_life_months', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=200)),
                ('record_pk', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_trail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatchCostDetail',
            fields=[
                ('batch_cost_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cost_head', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_doc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_doc_pk_bigint', models.BigIntegerField(blank=True, null=True)),
                ('source_doc_pk_uuid', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch_cost_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('bom_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('bom_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BomComponent',
            fields=[
                ('bom_component_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_per', models.DecimalField(decimal_places=6, max_digits=18)),
                ('scrap_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'bom_component',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('account_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.TextField()),
                ('is_posting', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrmActivity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrmLead',
            fields=[
                ('lead_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lead_code', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('lead_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_lead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('dn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dn_number', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('status', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('dn_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_delivered', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'delivery_note_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimBatch',
            fields=[
                ('batch_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('qc_released', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('company_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('base_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCostCenter',
            fields=[
                ('cost_center_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('cost_center_type', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_cost_center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCurrency',
            fields=[
                ('currency_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'dim_currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimItem',
            fields=[
                ('item_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_class', models.CharField(choices=[('INVENTORY', 'INVENTORY'), ('MANUFACTURED', 'MANUFACTURED'), ('SERVICE', 'SERVICE'), ('NON_INVENTORY', 'NON_INVENTORY'), ('KIT', 'KIT'), ('FIXED_ASSET', 'FIXED_ASSET')], max_length=30)),
                ('uom', models.CharField(max_length=20)),
                ('costing_method', models.CharField(blank=True, choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('AVERAGE', 'AVERAGE'), ('STANDARD', 'STANDARD'), ('SPECIFIC', 'SPECIFIC')], max_length=30, null=True)),
                ('is_batch_tracked', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTaxCode',
            fields=[
                ('tax_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('tax_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('is_vat', models.BooleanField(blank=True, null=True)),
                ('is_withholding', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_tax_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentApprovalHistory',
            fields=[
                ('approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_approval_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflowInstance',
            fields=[
                ('instance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('document_pk_bigint', models.BigIntegerField(blank=True, null=True)),
                ('document_pk_uuid', models.UUIDField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_workflow_instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('period_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_code', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiscal_period',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('fixed_asset_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=60, unique=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('start_depreciation_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fixed_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDepreciationLine',
            fields=[
                ('dep_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fixed_asset_depreciation_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDepreciationRun',
            fields=[
                ('dep_run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fixed_asset_depreciation_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlJournal',
            fields=[
                ('gl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('journal_number', models.CharField(max_length=50)),
                ('journal_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gl_journal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlLine',
            fields=[
                ('gl_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'gl_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('quantity_reserved', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'inventory_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('inv_txn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_type', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tx_date', models.DateTimeField(blank=True, null=True)),
                ('source_doc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_doc_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_type', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'invoice_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimsTestResult',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField()),
                ('parameter', models.CharField(max_length=200)),
                ('result_value', models.CharField(blank=True, max_length=200, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lims_test_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('party_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'party',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('allocation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'payment_allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollComponentLine',
            fields=[
                ('component_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_component_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollComponentType',
            fields=[
                ('component_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.TextField()),
                ('taxable', models.BooleanField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_component_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('pe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('payroll_run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCosting',
            fields=[
                ('product_costing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cost_version', models.TextField()),
                ('effective_date', models.DateField()),
                ('material_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('labor_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('overhead_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_cost', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('material_cost'), '+', models.F('labor_cost')), '+', models.F('overhead_cost')), output_field=models.DecimalField(decimal_places=6, max_digits=18))),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_costing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('prod_batch_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('planned_qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBilling',
            fields=[
                ('billing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('certified_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('retention_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retention_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_billing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectJob',
            fields=[
                ('project_job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('site_location', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectJobBudget',
            fields=[
                ('budget_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cost_head', models.TextField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_job_budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRetention',
            fields=[
                ('retention_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_retention_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('releasable_from', models.DateField(blank=True, null=True)),
                ('released', models.BooleanField(blank=True, null=True)),
                ('released_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_retention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('po_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'purchase_order_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('permission_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('permission', models.JSONField()),
                ('allowed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('routing_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_no', models.IntegerField()),
                ('operation_name', models.CharField(max_length=200)),
                ('work_center', models.CharField(blank=True, max_length=100, null=True)),
                ('std_setup_time', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('std_run_time', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cost_rate_per_hour', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'routing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('so_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('so_number', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('so_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'sales_order_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('tax_txn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tax_base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('posting_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tax_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseBin',
            fields=[
                ('bin_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('bin_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warehouse_bin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WithholdingTaxSetup',
            fields=[
                ('wht_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('applies_to', models.CharField(blank=True, max_length=20, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'withholding_tax_setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WithholdingTaxTransaction',
            fields=[
                ('wht_txn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('wht_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('posting_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'withholding_tax_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('workflow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('step_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_order', models.IntegerField()),
                ('role_required', models.CharField(blank=True, max_length=100, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_step',
                'managed': False,
            },
        ),
    ]
